---
- hosts: all
  tasks:
    - name: Install RHEL/Fedora Web Console (Cockpit)
      include_role:
        name: redhat.rhel_system_roles.cockpit
      vars:
        cockpit_packages: default
        #cockpit_packages: minimal
        #cockpit_packages: full

