---
- hosts: localhost
  tasks:
    - name: test lint
      shell: ansible-lint /tests/test.yml
      ignore_errors: true
      register: out
    
    - name: get ansible info
      shell: ansible-lint --version

#    - debug:
#        var: out
